### PR TITLE
domains, ports and urls support

### LINKED ISSUE #44: cdncheck domains, ports and urls support
https://github.com/projectdiscovery/cdncheck/issues/40#issuecomment-1201843235

```console
$ cat list.txt

hackerone.com
hackerone.com:443
https://hackerone.com
https://hackerone.com:443
104.16.100.52
104.16.100.52/32
104.16.100.52:443
https://104.16.100.52
https://104.16.100.52:443
```

```console
$ cat list.txt | ./cdncheck -resp

hackerone.com [waf] [cloudflare]
hackerone.com:443 [waf] [cloudflare]
https://hackerone.com [waf] [cloudflare]
https://hackerone.com:443 [waf] [cloudflare]
104.16.100.52 [waf] [cloudflare]
104.16.100.52/32 [waf] [cloudflare]
104.16.100.52:443 [waf] [cloudflare]
https://104.16.100.52 [waf] [cloudflare]
https://104.16.100.52:443 [waf] [cloudflare]
```

```json
echo https://docs.hackerone.com | ./cdncheck -json

{
  "timestamp": "2022-08-26T13:03:53.211756+05:30",
  "input": "https://docs.hackerone.com"
  "host": "docs.hackerone.com"
  "ip": "185.199.108.153",
  "cname": "hacker0x01.github.io",
  "cdn": true,
  "cdn_name": "github",
  "type": "cname"
}
```

```console
$ go install github.com/brenocss/whatcdn@latest

$ cat list.txt | whatcdn -t 20 -json
```

### PR DESCRIPTION
**Pull request by LuitelSamikshya**
closes #44

### CODE REVIEW

**Review by Ice3man543 — APPROVED** [review]

**Comment by brenocss** [comment]
Here I believe it would be better if we were using the dnsx libs which would accept multiple resolvers and different types of dns queries

**Comment by Mzack9999** [comment]
@brenocss Unfortunately I'm not sure it's actually possible as `dnsx` uses `cdncheck` (import loop)

**Comment by brenocss** [comment]
would be better if we deprecated the idead of cdncheck-cli, and use httpx and naabu for this purpose(cdn-check), cause it already do http request or dns requests with multiple resolvers and threads, and we could also save 1 dns request and 1 http request for each host. cdn-check would be just a lib that check for the http-response and dns response and check if is a cdn or not

**Comment by Mzack9999** [comment]
@brenocss I think it can still be handy for filtering ips/cidrs within a pipeline

**Comment by ehsandeep** [comment]
Closing as this needs to be reworked with updated information.

**Comment by brenocss** [comment]
> @brenocss Unfortunately I'm not sure it's actually possible as `dnsx` uses `cdncheck` (import loop)
Can't we use retryabledns?

**Pull request closed without merging**
