### PR TITLE
adding checkDnsResponse and fallback methods

### PR DESCRIPTION
**Pull request by brenocss**
## Proposed Changes

- refactor runner package to use cdncheck client methods
- cdncheck now resolves domain using retryableDNS instead of dialing with fastdialer [improved performance]
- cdncheck now has new option `-retry` to specify retry count while resolving
- cdncheck binary now automatically does a fallback check for waf
   - if no results were found with default cdncheck behaviour . and input is domain. cdncheck queries CNAME of domain
   - check if suffix of CNAME belongs to a WAF

### CODE REVIEW

**Comment by brenocss** [comment]
I can implement PTR checks as fallbacks for IPs. However, it is important to note that this method may not be entirely reliable.

**Review by ehsandeep — CHANGES_REQUESTED** [review]
Build fail

**Review by tarunKoyalwar — APPROVED** [review]
lgtm 

```console
$ chaos -d hackerone.com -silent |./cdncheck                                   130 ↵

            __           __              __  
  _________/ /___  _____/ /_  ___  _____/ /__
 / ___/ __  / __ \/ ___/ __ \/ _ \/ ___/ //_/
/ /__/ /_/ / / / / /__/ / / /  __/ /__/ ,<   
\___/\__,_/_/ /_/\___/_/ /_/\___/\___/_/|_|

		projectdiscovery.io

[INF] Current cdncheck version 1.0.0 (latest)
a.ns.hackerone.com
api.hackerone.com
b.ns.hackerone.com
gslink.hackerone.com
resources.hackerone.com
support.hackerone.com
www.hackerone.com
[INF] Found result: 7 (CDN: 1, CLOUD: 2, WAF: 4)
```

**Comment by tarunKoyalwar** [comment]
### New Changes
- refactor cdncheck to use new methods added in this PR
- cdncheck now resolves domain using retryableDNS instead of dialing with fastdialer [improved performance]
- cdncheck now has new option `-retry` to specify retry count while resolving

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
